name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  intl: 0.19.0
  flutter_blurhash: ^0.8.0
  google_fonts: ^6.2.1
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

fonts:
- family: Roboto
  fonts:
    - asset: fonts/Roboto-Bold.ttf
    - asset: fonts/Roboto-Regular.ttf

flutter:
  uses-material-design: true
